apiVersion: v1
kind: Pod
metadata:
  name: broken-test
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: container-0
  restartPolicy: Always
